package com.smartlab.erp.finance.enums;

public enum FinanceExpenseSubmissionType {
    PERSONAL_PROCUREMENT,
    PROJECT_TRAVEL_REIMBURSEMENT,
    PROJECT_HARDWARE_PROCUREMENT,
    PROJECT_EXTERNAL_TECH_SERVICE,
    PROJECT_REIMBURSEMENT
}
