FROM eclipse-temurin:17-jre

ARG APP_VERSION
LABEL org.opencontainers.image.version="${APP_VERSION}"
WORKDIR /app

ENV APP_UPLOADS_DIR=/app/uploads

RUN addgroup --system appgroup && adduser --system --ingroup appgroup appuser && mkdir -p /app/uploads && chown -R appuser:appgroup /app

COPY --chown=appuser:appgroup erp-backend-0.0.1-SNAPSHOT.jar /app/app.jar

USER appuser

EXPOSE 8101

ENTRYPOINT ["java", "-jar", "/app/app.jar"]
