# 由 SQLite 导出 — 编辑后建议 sync 回数据库
# 注意：主机与端口必须分开写
[servers]
srv1 ansible_host=89601a3c09fa1e57.natapp.cc ansible_port=12138
srv2 ansible_host=b9bb805314699f29.natapp.cc ansible_port=8887
srv3 ansible_host=47.93.215.230 ansible_port=6000

[servers:vars]
ansible_user=a
ansible_password=rjs12138
ansible_become_password=rjs12138
