[servers]
3090 ansible_host=192.168.66.41 ansible_port=22
4090 ansible_host=192.168.66.224 ansible_port=22
5090 ansible_host=192.168.66.223 ansible_port=22

[servers:vars]
ansible_user=a
ansible_password=rjs12138
ansible_become_password=rjs12138
