FROM nginx:1.27-alpine

ARG APP_VERSION
LABEL org.opencontainers.image.title="lab-erp-demo" \
      org.opencontainers.image.version="${APP_VERSION}"

COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
